'use client';

import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

export type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  isRTL: boolean;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      return (localStorage.getItem('pixelcode-lang') as Language) || 'en';
    }
    return 'en';
  });

  const isRTL = language === 'ar';

  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
    localStorage.setItem('pixelcode-lang', language);
  }, [language, isRTL]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  // Basic translation helper
  const t = (key: string): string => {
    const keys = key.split('.');
    let result: any = translations[language];
    
    for (const k of keys) {
      if (result && result[k]) {
        result = result[k];
      } else {
        return key; // Fallback to key if not found
      }
    }
    return result;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, isRTL, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};

// ─── Translations Dictionary ──────────────────────────────────────────────────

const translations: Record<Language, any> = {
  en: {
    common: {
      search: "Search...",
      notifications: "Notifications",
      allCaughtUp: "All caught up!",
      clearAll: "Clear all",
      save: "Save",
      cancel: "Cancel",
      loading: "Loading...",
      settings: "Settings",
      logout: "Logout",
      searchUsers: "Search users",
      changeLanguage: "Change Language",
      changeTheme: "Change Theme",
      collapseSidebar: "Collapse Sidebar",
      expandSidebar: "Expand Sidebar",
      viewAll: "View All",
      student: "Student",
      teacher: "Teacher",
      admin: "Admin",
      completed: "Completed",
      overview: "Overview",
      review: "Review",
      accept: "Accept",
      decline: "Decline",
      ignore: "Ignore",
      hoursShort: "h",
      minutesShort: "m",
      progress: "Progress",
      done: "Done",
      joinNow: "Join Now",
      getStarted: "Get Started",
      user: "User",
      level: "Level",
      xp: "XP",
      saving: "Saving...",
      learnMore: "Learn More",
      join: "Join",
      all: "All",
      easy: "Easy",
      medium: "Medium",
      hard: "Hard",
      expert: "Expert",
      create: "Create",
      manage: "Manage",
      open: "Open",
    },
    nav: {
      dashboard: "Dashboard",
      courses: "Courses",
      arena: "Arena",
      playground: "Playground",
      community: "Community",
      library: "Library",
      shop: "Shop",
      settings: "Settings",
      classroom: "Classroom",
      chat: "Smart Chat",
      admin: "Admin Panel",
      profile: "Profile",
    },
    notifications: {
      friendRequestSent: " sent you a friend request!",
      duelInviteSent: " invited you to a duel!",
      viewSocialHub: "View Social Hub",
      joinDuel: "Join Duel",
    },
    userMenu: {
      signedInAs: "Signed in as",
      myProfile: "My Profile",
    },
    dashboard: {
      welcome: "Welcome back",
      level: "Level",
      xpRemaining: "XP remaining",
      quickActions: "Quick Actions",
      recentActivity: "Recent Activity",
      codersOnline: "Coders Online",
      nextAchievement: "Next Achievement",
      totalXP: "Total XP",
      dayStreak: "Day Streak",
      rank: "Rank",
      profileSettings: "Profile Settings",
      activityEmpty: "Complete your first lesson to see activity here",
      getStarted: "Get started →",
      playgroundPromo: "Try the playground with any language",
      openPlayground: "Open playground →",
      challengePromo: "Solve your first challenge",
      browseChallenges: "Browse challenges →",
      globalLeaderboard: "Global Leaderboard",
      noFriends: "No friends yet",
      findFriends: "Find Friends",
      levelLabel: "Level {level}",
      rankLabel: "Rank {rank}",
      profileUpdated: "Profile updated!",
      failedUpdateProfile: "Failed to update profile",
      toGo: "{count} to go",
      loadingProfile: "Loading profile...",
      userNotFound: "User not found",
      goBack: "Go Back",
      joinedIn: "Joined PixelCode in {year}",
      challengeDuel: "Challenge to Duel",
      duelSent: "Duel Sent!",
      duelSentDesc: "Invited {name} to race!",
      recentAchievements: "Recent Achievements",
      statsActivity: "Stats & Activity",
      lockedAchievement: "Locked Achievement",
      activity: "Activity",
      ago_h: "{count}h ago",
      ago_d: "{count}d ago",
    },
    profile: {
      stats: "Stats",
      activity: "Activity",
      badges: "Badges",
      friends: "Friends",
      noFriends: "No friends yet",
      experience: "Experience",
      dayStreak: "Day Streak",
      rank: "Rank",
      profileSettings: "Profile Settings",
      chooseAvatar: "Choose your avatar",
      avatarDesc: "Pick a look that matches your coding style. You can change this later!",
      startCoding: "Start Coding",
      skipForNow: "Skip for now",
      profileUpdated: "Profile updated!",
      failedUpdateProfile: "Failed to update profile",
      toGo: "{count} to go",
      levelLabel: "Level {level}",
      rankLabel: "Rank {rank}",
      loadingProfile: "Loading profile...",
      userNotFound: "User not found",
      goBack: "Go Back",
      joinedIn: "Joined PixelCode in {year}",
      challengeDuel: "Challenge to Duel",
      duelSent: "Duel Sent!",
      duelSentDesc: "Invited {name} to race!",
      recentAchievements: "Recent Achievements",
      statsActivity: "Stats & Activity",
      lockedAchievement: "Locked Achievement",
      ago_h: "{count}h ago",
      ago_d: "{count}d ago",
    },
    social: {
      searchPlaceholder: "Search users by name...",
      noUsersFound: "No users found matching",
      typeToSearch: "Type to search",
      searchHint: "Find your friends and challenge them to a duel!",
      friendRequestSent: "Friend request sent to {name}",
      requestSent: "Request Sent",
    },
    chat: {
      newChat: "New Chat",
      searchPlaceholder: "Search chats...",
      noChatsMatch: "No chats match your search",
      noChatsYet: "No chats yet. Start a new one!",
      aiName: "PixelCode AI",
      aiDesc: "Your personal programming tutor",
      inputPlaceholder: "Ask anything about programming... (Enter to send)",
      poweredBy: "Powered by Gemini 2.0 Flash · Responses may not always be accurate",
      signInToSave: "Sign in to save your chat history",
      untitled: "Untitled Chat",
      suggestions: [
        "Explain recursion with an example",
        "Debug my Python code",
        "What is the difference between == and ===?",
        "How do I reverse a string in Java?",
      ],
    },
    classroom: {
      title: "Classroom",
      createDesc: "Create and manage your classrooms",
      joinDesc: "Join and view your enrolled classrooms",
      createButton: "Create Classroom",
      joinButton: "Join",
      joinTitle: "Join a Classroom",
      joinCodePlaceholder: "Enter 6-character join code",
      noClassroomsYet: "No classrooms yet",
      noEnrolledClassrooms: "No enrolled classrooms",
      createFirstClassroom: "Create your first classroom to get started",
      askTeacherCode: "Ask your teacher for a join code",
      studentsEnrolled: "{count} students enrolled",
      byTeacher: "By {name}",
      createModalTitle: "Create New Classroom",
      nameLabel: "Classroom Name *",
      namePlaceholder: "e.g. Python Beginners 2024",
      descLabel: "Description",
      descPlaceholder: "What will students learn?",
      failedCreate: "Failed to create classroom. Please try again.",
      failedJoin: "Failed to join. Please try again.",
      noClassroomFound: "No classroom found with this code.",
      alreadyEnrolled: "You are already enrolled in this classroom.",
      joinCodeLabel: "Join code:",
      copyCode: "Copy join code",
      addAssignment: "Add Assignment",
      backToClassrooms: "Back to Classrooms",
      taughtBy: "Taught by {name}",
      studentsCount: "{count} students",
      assignmentsCount: "{count} assignments",
      assignmentsTab: "📋 Assignments",
      studentsTab: "👥 Students",
      noAssignmentsYet: "No assignments yet",
      addFirstAssignment: "Add your first assignment above",
      noStudentsYet: "No students yet",
      shareJoinCode: "Share the join code to invite students",
      assignmentTitleLabel: "Title *",
      assignmentTitlePlaceholder: "Assignment title",
      assignmentDescLabel: "Description",
      assignmentDescPlaceholder: "What should students do?",
      dueDateLabel: "Due Date (optional)",
      due: "Due:",
      studentLabel: "Student {index}",
      addAssignmentButton: "Add Assignment",
      notFound: "Classroom not found.",
    },
    settings: {
      title: "Settings",
      subtitle: "Manage your account and preferences",
      appearance: "Appearance",
      appearanceDesc: "Choose a preset theme or create your own below",
      themeLab: "Theme Lab (Beta)",
      themeLabDesc: "Design your perfect workspace with custom colors",
      notifications: "Notifications",
      emailNotifs: "Email Notifications",
      emailNotifsDesc: "Receive updates and announcements via email",
      account: "Account",
      email: "Email",
      role: "Role",
      memberSince: "Member since",
      dangerZone: "Danger Zone",
      deleteAccount: "Delete Account",
      deleteDesc: "Permanently delete your account and all associated data. This cannot be undone.",
      deleteConfirm: "Are you absolutely sure?",
      deleteWarning1: "Your profile and all XP will be deleted",
      deleteWarning2: "Your chat history will be deleted",
      deleteWarning3: "Your course progress will be deleted",
      deleteWarning4: "This action cannot be undone",
      typeDelete: "Type DELETE to confirm:",
      confirmDelete: "Confirm Delete",
      cancel: "Cancel",
      accountDeleted: "Account deleted",
      reloginRequired: "Please sign out and sign back in before deleting your account.",
      deleteFailed: "Failed to delete account. Please try again.",
    },
    landing: {
      heroTitle: "Learn to code, pixel by pixel",
      heroSub: "PixelCode turns complex programming concepts into small, manageable pieces. Master 13+ languages with AI assistance, live coding, and real challenges.",
      startFree: "Start for free",
      goDashboard: "Go to Dashboard",
      kidsMode: "Kids Mode",
      features: "Features",
      languages: "Languages",
      about: "About",
      nowWithAi: "Now with AI-powered tutoring",
      freeForever: "No credit card required · Free forever plan available",
      stats: {
        languages: "Languages Supported",
        exercises: "Exercises & Challenges",
        aiTutoring: "Powered Tutoring"
      },
      everythingYouNeed: "Everything you need to learn",
      platformTools: "One platform. All the tools. From absolute beginner to advanced developer.",
      journeyToday: "Start your journey today",
      joinMillions: "Join millions of learners worldwide and master the skill of the future.",
      featuresList: {
        aiTutor: { title: "AI Tutor", desc: "Get instant help, code reviews, and error explanations from your AI assistant." },
        liveCompiler: { title: "Live Compiler", desc: "Write and run code in 13+ languages directly in the browser — no setup needed." },
        challenges: { title: "Challenges", desc: "Sharpen your skills with real coding challenges across all difficulty levels." },
        classrooms: { title: "Classrooms", desc: "Teachers can create classrooms, assign tasks, and track student progress." },
        courses: { title: "Structured Courses", desc: "Follow a pixel-by-pixel learning path from beginner to advanced." },
        kidsMode: { title: "Kids Mode", desc: "A fun, colorful experience teaching CS basics, math, and mind games." },
      }
    },
    about: {
      ourVision: "Our Vision",
      heroTitle: "Learning to code pixel by pixel",
      heroSub: "We believe that programming is the superpower of the 21st century. Our mission is to make it accessible, gamified, and powered by the latest AI technology.",
      stats: {
        learners: "Active Learners",
        loc: "Lines of Code",
        challenges: "Challenges",
        success: "Success Rate"
      },
      whyTitle: "A platform built for the next generation",
      aiLearning: { title: "AI-Powered Learning", desc: "Our intelligent tutor understands your code and provides human-like feedback in real-time." },
      gamified: { title: "Gamified Progression", desc: "Earn XP, unlock badges, and climb the leaderboard as you master new concepts." },
      realTools: { title: "Real-World Tools", desc: "No simplified blocks. Use actual code with our professional-grade live compiler." },
      joinRevolution: "Join the revolution",
      footerSub: "Whether you're a absolute beginner or a pro looking to sharpen your skills, there's a place for you at PixelCode.",
      getStarted: "Get Started Now",
    },
    auth: {
      welcomeBack: "Welcome Back",
      loginSub: "Log in to continue your coding journey",
      createAccount: "Create Account",
      signupSub: "Join the future of learning — free forever",
      orUseEmail: "or use email",
      orCreateAccount: "or create account",
      emailAddress: "Email address",
      password: "Password",
      confirmPassword: "Confirm password",
      displayName: "Display name",
      signIn: "Sign In",
      signUp: "Sign Up",
      newHere: "New here?",
      oneOfUs: "One of us?",
      signupMsg: "Signup and discover a great amount of new opportunities!",
      signinMsg: "If you already have an account, just sign in. We've missed you!",
      dontHaveAccount: "Don't have an account?",
      alreadyHaveAccount: "Already have an account?",
      joinClub: "Join the club",
      loginLink: "Log in",
      backToHome: "Back to Home",
      passwordsDoNotMatch: "Passwords do not match.",
      passwordTooWeak: "Password is too weak — please use at least 6 characters.",
      strengthWeak: "Weak",
      strengthGood: "Good",
      strengthStrong: "Strong",
    },
    arena: {
      hubTitle: "Competitive Arena",
      hubSub: "Prove your skills in real-time challenges and duels.",
      liveArena: "Live Arena",
      tagline: "Prove Your Coding Might",
      description: "Compete in real-time duels, solve daily challenges, and climb the global rankings.",
      training: "Training Grounds",
      duels: "Duel Zone",
      rankings: "Hall of Fame",
      activeRooms: "Active Rooms",
      findDuel: "Find a Duel",
      dailyQuest: "Daily Quest",
      endsIn: "Ends in:",
      acceptQuest: "Accept Quest",
      matchHistory: "Match History",
      topGladiators: "Top Gladiators",
      rating: "Rating",
      unranked: "UNRANKED",
      noRecentDuels: "No recent duels. Go find an opponent!",
      arenaGladiator: "Arena Gladiator",
      win3Duels: "Win 3 Duels",
      duelsWon: "Duels Won",
      globalRank: "Global Rank",
      expertLogic: "Expert Logic",
      recursiveFibTitle: "Recursive Fibonacci Optimization",
      recursiveFibDesc: "Can you find the most efficient way to calculate the 50th Fibonacci number without causing a stack overflow?",
      joined: "joined",
      viewAllRankings: "View All Rankings",
      trainingSub: "Sharpen your skills before entering the Duel Zone.",
      challengesAvailable: "{count} challenges available",
      searchChallenges: "Search challenges...",
      allLanguages: "All Languages",
      noChallengesYet: "No challenges yet",
      noChallengesMatch: "No challenges match your filters",
      addChallengesDesc: "Add challenges to the Firestore 'challenges' collection",
      tryDifferentFilters: "Try different filters or clear your search",
      showingOf: "Showing {count} of {total} challenges",
      startTraining: "Start Training",
      correct: "Correct!",
      notQuite: "Not quite!",
      xpEarned: "+{count} XP earned!",
      correctAnswerLabel: "Correct answer:",
      review: "Review",
      more: "More",
      chooseAnswer: "Choose the correct answer",
      whyNot: "Why not?",
      gettingHint: "Getting hint...",
      getHintPenalty: "Get a hint (–5 XP penalty)",
      viewResult: "View Result",
      moreTraining: "More Training",
      hintLabel: "Hint",
      thinkCarefully: "Think carefully about the key concepts involved in this challenge!",
    },
    courses: {
      title: "Learning Path",
      sub: "Master programming through interactive, bite-sized lessons.",
      continue: "Continue Learning",
      allCourses: "All Courses",
      of: "of",
      coursesCount: "courses",
      beginner: "Beginner",
      intermediate: "Intermediate",
      advanced: "Advanced",
      allLevels: "All Levels",
      catalogUnavailable: "Course catalog unavailable",
      noCoursesMatch: "No courses match your filters",
      tryDifferentFilters: "Try a different language, level, or search term.",
      lessons: "lessons",
      readyToStart: "Ready to start",
      startCourse: "Start Course",
      reviewCourse: "Review Course",
      lessonNotFound: "Lesson not found",
      courseNotFound: "Course not found",
      backToCourses: "Back to Courses",
      courseOverview: "Course Overview",
      markComplete: "Mark Complete",
      estimatedTime: "estimated time",
      quizzes: "quizzes",
      knowledgeCheck: "Knowledge Check",
      questions: "Questions",
      lessonComplete: "Lesson Complete!",
      xpEarned: "XP earned",
      nextLesson: "Next Lesson",
      previousLesson: "Previous Lesson",
      backToCourse: "Back to Course",
      correct: "Correct",
      incorrect: "Incorrect",
      greatWork: "Great work — lesson already marked complete!",
      markCompleteToEarn: "Mark the lesson complete to earn your XP",
      reviewLessons: "Review Lessons",
      pathTip: "Complete them in order for the smoothest path.",
      lessonLocked: "Complete the previous lesson to unlock",
      about: "About",
    },
    playground: {
      aiReview: "AI Review",
      run: "Run",
      output: "Output",
      emptyOutput: "Click Run to execute your code",
      resetCode: "Reset to starter code",
      copyCode: "Copy code",
    },
  },
  ar: {
    common: {
      search: "بحث...",
      notifications: "التنبيهات",
      allCaughtUp: "كل شيء جاهز!",
      clearAll: "مسح الكل",
      save: "حفظ",
      cancel: "إلغاء",
      loading: "جاري التحميل...",
      settings: "الإعدادات",
      logout: "تسجيل الخروج",
      searchUsers: "البحث عن المستخدمين",
      changeLanguage: "تغيير اللغة",
      changeTheme: "تغيير السمة",
      collapseSidebar: "تصغير القائمة",
      expandSidebar: "توسيع القائمة",
      viewAll: "عرض الكل",
      student: "طالب",
      teacher: "معلم",
      admin: "مسؤول",
      completed: "مكتمل",
      overview: "نظرة عامة",
      review: "مراجعة",
      accept: "قبول",
      decline: "رفض",
      ignore: "تجاهل",
      hoursShort: " ساعة",
      minutesShort: " دقيقة",
      progress: "التقدم",
      done: "تم",
      joinNow: "انضم الآن",
      getStarted: "ابدأ الآن",
      user: "مستخدم",
      level: "المستوى",
      xp: "نقطة خبرة",
      saving: "جاري الحفظ...",
      back: "رجوع",
      next: "التالي",
      confirm: "تأكيد",
      learnMore: "تعلم المزيد",
      join: "انضمام",
      all: "الكل",
      easy: "سهل",
      medium: "متوسط",
      hard: "صعب",
      expert: "خبير",
      share: "مشاركة",
      failed: "فشل",
      create: "إنشاء",
      manage: "إدارة",
      open: "فتح",
    },
    nav: {
      dashboard: "لوحة التحكم",
      courses: "الدورات",
      arena: "الساحة",
      playground: "المختبر",
      community: "المجتمع",
      library: "المكتبة",
      shop: "المتجر",
      settings: "الإعدادات",
      classroom: "الفصل الدراسي",
      chat: "الدردشة الذكية",
      admin: "لوحة الإدارة",
      profile: "الملف الشخصي",
    },
    notifications: {
      friendRequestSent: " أرسل لك طلب صداقة!",
      duelInviteSent: " دعاك لمبارزة!",
      viewSocialHub: "عرض المركز الاجتماعي",
      joinDuel: "انضم للمبارزة",
    },
    userMenu: {
      signedInAs: "مسجل الدخول باسم",
      myProfile: "ملفي الشخصي",
    },
    dashboard: {
      welcome: "مرحباً بك مجدداً",
      level: "المستوى",
      xpRemaining: "XP متبقي",
      quickActions: "إجراءات سريعة",
      recentActivity: "النشاط الأخير",
      codersOnline: "المبرمجون المتصلون",
      nextAchievement: "الإنجاز القادم",
      totalXP: "إجمالي النقاط",
      dayStreak: "سلسلة الأيام",
      rank: "المركز",
      profileSettings: "إعدادات الملف الشخصي",
      activityEmpty: "أكمل درسك الأول لرؤية النشاط هنا",
      getStarted: "ابدأ الآن ←",
      playgroundPromo: "جرب المختبر بأي لغة برمجة",
      openPlayground: "فتح المختبر ←",
      challengePromo: "حل التحدي الأول الخاص بك",
      browseChallenges: "تصفح التحديات ←",
      globalLeaderboard: "قائمة المتصدرين العالمية",
      noFriends: "لا يوجد أصدقاء بعد",
      findFriends: "البحث عن أصدقاء",
      levelLabel: "المستوى {level}",
      rankLabel: "المركز {rank}",
      profileUpdated: "تم تحديث الملف الشخصي!",
      failedUpdateProfile: "فشل تحديث الملف الشخصي",
      toGo: "يتبقى {count}",
      loadingProfile: "جاري تحميل الملف الشخصي...",
      userNotFound: "المستخدم غير موجود",
      goBack: "الرجوع",
      joinedIn: "انضم إلى PixelCode في {year}",
      challengeDuel: "تحدي للمبارزة",
      duelSent: "تم إرسال المبارزة!",
      duelSentDesc: "تمت دعوة {name} للسباق!",
      recentAchievements: "الإنجازات الأخيرة",
      statsActivity: "الإحصائيات والنشاط",
      lockedAchievement: "إنجاز مقفل",
      activity: "النشاط",
      ago_h: "منذ {count} س",
      ago_d: "منذ {count} ي",
    },
    settings: {
      title: "الإعدادات",
      subtitle: "إدارة حسابك وتفضيلاتك",
      appearance: "المظهر",
      appearanceDesc: "اختر مظهراً معداً مسبقاً أو أنشئ مظهرك الخاص أدناه",
      themeLab: "مختبر المظهر (تجريبي)",
      themeLabDesc: "صمم مساحة عملك المثالية بألوان مخصصة",
      notifications: "التنبيهات",
      emailNotifs: "تنبيهات البريد الإلكتروني",
      emailNotifsDesc: "تلقي التحديثات والإعلانات عبر البريد الإلكتروني",
      account: "الحساب",
      email: "البريد الإلكتروني",
      role: "الدور",
      memberSince: "عضو منذ",
      dangerZone: "منطقة الخطر",
      deleteAccount: "حذف الحساب",
      deleteDesc: "حذف حسابك وجميع البيانات المرتبطة به نهائياً. لا يمكن التراجع عن هذا الإجراء.",
      deleteConfirm: "هل أنت متأكد تماماً؟",
      deleteWarning1: "سيتم حذف ملفك الشخصي وجميع نقاط XP",
      deleteWarning2: "سيتم حذف سجل الدردشة الخاص بك",
      deleteWarning3: "سيتم حذف تقدمك في الدورات",
      deleteWarning4: "هذا الإجراء لا يمكن التراجع عنه",
      typeDelete: "اكتب DELETE للتأكيد:",
      confirmDelete: "تأكيد الحذف",
      cancel: "إلغاء",
      accountDeleted: "تم حذف الحساب",
      reloginRequired: "يرجى تسجيل الخروج والعودة مرة أخرى قبل حذف حسابك.",
      deleteFailed: "فشل حذف الحساب. يرجى المحاولة مرة أخرى.",
    },
    arena: {
      hubTitle: "ساحة المنافسة",
      hubSub: "أثبت مهاراتك في تحديات ومبارزات مباشرة.",
      liveArena: "الساحة المباشرة",
      tagline: "أثبت قوتك في البرمجة",
      description: "تنافس في مبارزات مباشرة، وحل التحديات اليومية، وتسلق الترتيب العالمي.",
      training: "ميادين التدريب",
      duels: "منطقة المبارزة",
      rankings: "قاعة المشاهير",
      activeRooms: "الغرف النشطة",
      findDuel: "ابحث عن مبارزة",
      dailyQuest: "المهمة اليومية",
      endsIn: "تنتهي في:",
      acceptQuest: "قبول المهمة",
      matchHistory: "تاريخ المباريات",
      topGladiators: "أفضل المحاربين",
      rating: "التقييم",
      unranked: "غير مصنف",
      noRecentDuels: "لا توجد مبارزات حديثة. اذهب وابحث عن خصم!",
      arenaGladiator: "مبارز الساحة",
      win3Duels: "فز بـ 3 مبارزات",
      duelsWon: "المبارزات التي فزت بها",
      globalRank: "الترتيب العالمي",
      expertLogic: "منطق خبير",
      recursiveFibTitle: "تحسين متتالية فيبوناتشي التكرارية",
      recursiveFibDesc: "هل يمكنك العثور على الطريقة الأكثر كفاءة لحساب رقم فيبوناتشي الخمسين دون التسبب في تجاوز سعة المكدس؟",
      joined: "انضموا",
      viewAllRankings: "عرض جميع التصنيفات",
      trainingSub: "اشحذ مهاراتك قبل دخول منطقة المبارزة.",
      challengesAvailable: "{count} تحدي متاح",
      searchChallenges: "البحث عن التحديات...",
      allLanguages: "جميع اللغات",
      noChallengesYet: "لا توجد تحديات بعد",
      noChallengesMatch: "لا توجد تحديات تطابق عوامل التصفية الخاصة بك",
      addChallengesDesc: "أضف تحديات إلى مجموعة Firestore 'challenges'",
      tryDifferentFilters: "جرب عوامل تصفية مختلفة أو امسح بحثك",
      showingOf: "عرض {count} من أصل {total} تحدي",
      startTraining: "ابدأ التدريب",
      correct: "صحيح!",
      notQuite: "ليس تماماً!",
      xpEarned: "+{count} XP كسبت!",
      correctAnswerLabel: "الإجابة الصحيحة:",
      review: "مراجعة",
      more: "المزيد",
      chooseAnswer: "اختر الإجابة الصحيحة",
      whyNot: "لماذا لا؟",
      gettingHint: "جاري الحصول على تلميح...",
      getHintPenalty: "احصل على تلميح (خصم ٥ XP)",
      viewResult: "عرض النتيجة",
      moreTraining: "مزيد من التدريب",
      hintLabel: "تلميح",
      thinkCarefully: "فكر جيداً في المفاهيم الأساسية المرتبطة بهذا التحدي!",
    },
    courses: {
      title: "مسار التعلم",
      sub: "أتقن البرمجة من خلال دروس تفاعلية ومبسطة.",
      continue: "مواصلة التعلم",
      allCourses: "جميع الدورات",
      of: "من",
      coursesCount: "دورة",
      beginner: "مبتدئ",
      intermediate: "متوسط",
      advanced: "متقدم",
      allLevels: "جميع المستويات",
      catalogUnavailable: "كتالوج الدورات غير متوفر حالياً",
      noCoursesMatch: "لا توجد دورات تطابق معايير البحث",
      tryDifferentFilters: "حاول تغيير اللغة أو المستوى أو كلمة البحث.",
      lessons: "دروس",
      readyToStart: "جاهز للبدء",
      startCourse: "ابدأ الدورة",
      reviewCourse: "مراجعة الدورة",
      lessonNotFound: "الدرس غير موجود",
      courseNotFound: "الدورة غير موجودة",
      backToCourses: "العودة إلى الدورات",
      courseOverview: "نظرة عامة على الدورة",
      markComplete: "تحديد كمكتمل",
      estimatedTime: "الوقت المقدر",
      quizzes: "اختبارات",
      knowledgeCheck: "التحقق من المعرفة",
      questions: "أسئلة",
      lessonComplete: "اكتمل الدرس!",
      xpEarned: "XP تم كسبها",
      nextLesson: "الدرس التالي",
      previousLesson: "الدرس السابق",
      backToCourse: "العودة إلى الدورة",
      correct: "إجابة صحيحة",
      incorrect: "غير صحيح",
      greatWork: "عمل رائع — تم وضع علامة اكتمال على الدرس بالفعل!",
      markCompleteToEarn: "ضع علامة اكتمال على الدرس لتكسب نقاط XP",
      reviewLessons: "مراجعة الدروس",
      pathTip: "أكملها بالترتيب للحصول على أفضل مسار.",
      lessonLocked: "أكمل الدرس السابق لفتح هذا الدرس",
      about: "حوالي",
    },
    playground: {
      aiReview: "مراجعة الذكاء الاصطناعي",
      run: "تشغيل",
      output: "المخرجات",
      emptyOutput: "انقر فوق تشغيل لتنفيذ الكود الخاص بك",
      resetCode: "إعادة تعيين الكود",
      copyCode: "نسخ الكود",
    },
    landing: {
      heroTitle: "تعلم البرمجة، بكسل تلو الآخر",
      heroSub: "PixelCode يحول مفاهيم البرمجة المعقدة إلى أجزاء صغيرة وسهلة الاستيعاب. أتقن أكثر من 13 لغة بمساعدة الذكاء الاصطناعي، والبرمجة المباشرة، والتحديات الحقيقية.",
      startFree: "ابدأ مجاناً",
      goDashboard: "الذهاب إلى لوحة التحكم",
      kidsMode: "وضع الأطفال",
      features: "المميزات",
      languages: "اللغات",
      about: "عن المنصة",
      nowWithAi: "الآن مع تدريس مدعوم بالذكاء الاصطناعي",
      freeForever: "لا حاجة لبطاقة ائتمان · تتوفر خطة مجانية للأبد",
      stats: {
        languages: "لغة مدعومة",
        exercises: "تمرين وتحدي",
        aiTutoring: "تدريس ذكي"
      },
      everythingYouNeed: "كل ما تحتاجه للتعلم",
      platformTools: "منصة واحدة. كل الأدوات. من المبتدئ تماماً إلى المطور المتقدم.",
      journeyToday: "ابدأ رحلتك اليوم",
      joinMillions: "انضم إلى ملايين المتعلمين حول العالم وأتقن مهارة المستقبل.",
      featuresList: {
        aiTutor: { title: "مدرب ذكي", desc: "احصل على مساعدة فورية، ومراجعات للكود، وشروحات للأخطاء من مساعدك الذكي." },
        liveCompiler: { title: "مترجم مباشر", desc: "اكتب وشغل الكود في أكثر من 13 لغة مباشرة في المتصفح — لا حاجة للإعداد." },
        challenges: { title: "تحديات", desc: "اشحذ مهاراتك مع تحديات برمجة حقيقية عبر جميع مستويات الصعوبة." },
        classrooms: { title: "فصول دراسية", desc: "يمكن للمعلمين إنشاء فصول دراسية وتكليف المهام وتتبع تقدم الطلاب." },
        courses: { title: "دورات منظمة", desc: "اتبع مسار تعلم بكسل تلو الآخر من المبتدئ إلى المتقدم." },
        kidsMode: { title: "وضع الأطفال", desc: "تجربة ممتعة وملونة لتعليم أساسيات علوم الكمبيوتر والرياضيات وألعاب العقل." },
      }
    },
    about: {
      ourVision: "رؤيتنا",
      heroTitle: "تعلم البرمجة بكسل تلو الآخر",
      heroSub: "نحن نؤمن بأن البرمجة هي القوة الخارقة للقرن الحادي والعشرين. مهمتنا هي جعلها سهلة الوصول، وممتعة، ومدعومة بأحدث تقنيات الذكاء الاصطناعي.",
      stats: {
        learners: "متعلم نشط",
        loc: "سطر كود",
        challenges: "تحدي",
        success: "معدل النجاح"
      },
      whyTitle: "منصة مبنية للجيل القادم",
      aiLearning: { title: "تعلم مدعوم بالذكاء الاصطناعي", desc: "يفهم مدربنا الذكي كودك ويقدم ملاحظات تشبه ملاحظات البشر في الوقت الفعلي." },
      gamified: { title: "تقدم ممتع", desc: "اكسب نقاط XP، وافتح الأوسمة، وتسلق قائمة المتصدرين بينما تتقن مفاهيم جديدة." },
      realTools: { title: "أدوات حقيقية", desc: "لا توجد قوالب مبسطة. استخدم كوداً حقيقياً مع مترجمنا المباشر من الدرجة الاحترافية." },
      joinRevolution: "انضم إلى الثورة",
      footerSub: "سواء كنت مبتدئاً تماماً أو محترفاً يتطلع لشحذ مهاراته، هناك مكان لك في PixelCode.",
      getStarted: "ابدأ الآن",
    },
    auth: {
      welcomeBack: "مرحباً بعودتك",
      loginSub: "سجل الدخول لمواصلة رحلتك في البرمجة",
      createAccount: "إنشاء حساب",
      signupSub: "انضم إلى مستقبل التعلم — مجاني للأبد",
      orUseEmail: "أو استخدم البريد الإلكتروني",
      orCreateAccount: "أو أنشئ حساباً",
      emailAddress: "البريد الإلكتروني",
      password: "كلمة المرور",
      confirmPassword: "تأكيد كلمة المرور",
      displayName: "اسم العرض",
      signIn: "تسجيل الدخول",
      signUp: "إنشاء حساب",
      newHere: "جديد هنا؟",
      oneOfUs: "عضو معنا؟",
      signupMsg: "سجل الآن واكتشف كمية كبيرة من الفرص الجديدة!",
      signinMsg: "إذا كان لديك حساب بالفعل، فقط سجل الدخول. لقد افتقدناك!",
      dontHaveAccount: "ليس لديك حساب؟",
      alreadyHaveAccount: "لديك حساب بالفعل؟",
      joinClub: "انضم إلى النادي",
      loginLink: "سجل الدخول",
      backToHome: "العودة للرئيسية",
      passwordsDoNotMatch: "كلمات المرور غير متطابقة.",
      passwordTooWeak: "كلمة المرور ضعيفة جداً - يرجى استخدام 6 أحرف على الأقل.",
      strengthWeak: "ضعيف",
      strengthGood: "جيد",
      strengthStrong: "قوي",
    },
    profile: {
      stats: "الإحصائيات",
      activity: "النشاط",
      badges: "الأوسمة",
      friends: "الأصدقاء",
      noFriends: "لا يوجد أصدقاء بعد",
      experience: "الخبرة",
      dayStreak: "سلسلة الأيام",
      rank: "المركز",
      profileSettings: "إعدادات الملف الشخصي",
      chooseAvatar: "اختر صورتك الرمزية",
      avatarDesc: "اختر مظهراً يناسب أسلوبك في البرمجة. يمكنك تغيير هذا لاحقاً!",
      startCoding: "ابدأ البرمجة",
      skipForNow: "تخطي الآن",
      requests: "طلبات الصداقة",
      pendingRequests: "لديك {count} طلبات معلقة بانتظارك!",
      coursesStarted: "بدأ الدورات",
      challengesSolved: "التحديات المحلولة",
      lessonsCompleted: "الدروس المكتملة",
      findFriends: "البحث عن أصدقاء",
      level: "المستوى",
      profileUpdated: "تم تحديث الملف الشخصي!",
      failedUpdateProfile: "فشل تحديث الملف الشخصي",
      toGo: "يتبقى {count}",
      levelLabel: "المستوى {level}",
      rankLabel: "المركز {rank}",
      loadingProfile: "جاري تحميل الملف الشخصي...",
      userNotFound: "المستخدم غير موجود",
      goBack: "الرجوع",
      joinedIn: "انضم إلى PixelCode في {year}",
      challengeDuel: "تحدي للمبارزة",
      duelSent: "تم إرسال المبارزة!",
      duelSentDesc: "تمت دعوة {name} للسباق!",
      recentAchievements: "الإنجازات الأخيرة",
      statsActivity: "الإحصائيات والنشاط",
      lockedAchievement: "إنجاز مقفل",
      ago_h: "منذ {count} س",
      ago_d: "منذ {count} ي",
    },
    social: {
      searchPlaceholder: "البحث عن المستخدمين بالاسم...",
      noUsersFound: "لم يتم العثور على مستخدمين يطابقون",
      typeToSearch: "اكتب للبحث",
      searchHint: "ابحث عن أصدقائك وتحدَّهم في مبارزة!",
      friendRequestSent: "تم إرسال طلب صداقة إلى {name}",
      requestSent: "تم إرسال الطلب",
    },
    chat: {
      newChat: "محادثة جديدة",
      searchPlaceholder: "البحث في المحادثات...",
      noChatsMatch: "لا توجد محادثات تطابق بحثك",
      noChatsYet: "لا توجد محادثات بعد. ابدأ واحدة جديدة!",
      aiName: "PixelCode AI",
      aiDesc: "معلم البرمجة الشخصي الخاص بك",
      inputPlaceholder: "اسأل أي شيء عن البرمجة... (اضغط Enter للإرسال)",
      poweredBy: "مدعوم من Gemini 2.0 Flash · قد لا تكون الاستجابات دقيقة دائماً",
      signInToSave: "سجل الدخول لحفظ سجل المحادثات",
      untitled: "محادثة بدون عنوان",
      suggestions: [
        "اشرح العودية (recursion) مع مثال",
        "صحح كود بايثون الخاص بي",
        "ما الفرق بين == و ===؟",
        "كيف أعكس سلسلة نصية في جافا؟",
      ],
    },
    classroom: {
      title: "الفصل الدراسي",
      createDesc: "إنشاء وإدارة فصولك الدراسية",
      joinDesc: "انضم إلى فصولك الدراسية واستعرضها",
      createButton: "إنشاء فصل دراسي",
      joinButton: "انضمام",
      joinTitle: "انضم إلى فصل دراسي",
      joinCodePlaceholder: "أدخل رمز الانضمام المكون من 6 أحرف",
      noClassroomsYet: "لا توجد فصول دراسية بعد",
      noEnrolledClassrooms: "لم تنضم إلى أي فصول دراسية",
      createFirstClassroom: "أنشئ أول فصل دراسي لك للبدء",
      askTeacherCode: "اطلب من معلمك رمز الانضمام",
      studentsEnrolled: "{count} طلاب مسجلين",
      byTeacher: "بواسطة {name}",
      createModalTitle: "إنشاء فصل دراسي جديد",
      nameLabel: "اسم الفصل الدراسي *",
      namePlaceholder: "مثال: مبرمجي بايثون 2024",
      descLabel: "الوصف",
      descPlaceholder: "ماذا سيتعلم الطلاب؟",
      failedCreate: "فشل إنشاء الفصل الدراسي. يرجى المحاولة مرة أخرى.",
      failedJoin: "فشل الانضمام. يرجى المحاولة مرة أخرى.",
      noClassroomFound: "لا يوجد فصل دراسي بهذا الرمز.",
      alreadyEnrolled: "أنت مسجل بالفعل في هذا الفصل الدراسي.",
      joinCodeLabel: "رمز الانضمام:",
      copyCode: "نسخ رمز الانضمام",
      addAssignment: "إضافة تكليف",
      backToClassrooms: "الرجوع للفصول الدراسية",
      taughtBy: "بواسطة {name}",
      studentsCount: "{count} طلاب",
      assignmentsCount: "{count} تكليفات",
      assignmentsTab: "📋 التكليفات",
      studentsTab: "👥 الطلاب",
      noAssignmentsYet: "لا توجد تكليفات بعد",
      addFirstAssignment: "أضف تكليفك الأول أعلاه",
      noStudentsYet: "لا يوجد طلاب بعد",
      shareJoinCode: "شارك رمز الانضمام لدعوة الطلاب",
      assignmentTitleLabel: "العنوان *",
      assignmentTitlePlaceholder: "عنوان التكليف",
      assignmentDescLabel: "الوصف",
      assignmentDescPlaceholder: "ماذا يجب على الطلاب فعله؟",
      dueDateLabel: "تاريخ الاستحقاق (اختياري)",
      due: "موعد التسليم:",
      studentLabel: "طالب {index}",
      addAssignmentButton: "إضافة تكليف",
      notFound: "الفصل الدراسي غير موجود.",
    },
  }
};
