export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  ABOUT: '/about',
  APP: {
    DASHBOARD: '/app',
    COURSES: '/app/courses',
    COURSE_DETAIL: '/app/courses/:slug',
    LESSON: '/app/lesson/:lessonSlug',
    PLAYGROUND: '/app/playground',
    ARENA: '/app/arena',
    TRAINING: '/app/arena/training',
    TRAINING_DETAIL: '/app/arena/training/:slug',
    DUELS: '/app/arena/duels',
    DUEL_ROOM: '/app/arena/duels/:roomId',
    RANKINGS: '/app/arena/rankings',
    CLASSROOM: '/app/classroom',
    CLASSROOM_DETAIL: '/app/classroom/:id',
    CHAT: '/app/chat',
    PROFILE: '/app/profile',
    PUBLIC_PROFILE: '/app/profile/:uid',
    SETTINGS: '/app/settings',
    LIBRARY: '/app/library',
    CHALLENGES: '/app/challenges',
  },
  ADMIN: {
    DASHBOARD: '/admin',
    USERS: '/admin/users',
    CHALLENGES: '/admin/challenges',
    SEED: '/admin/seed',
    COURSES: '/admin/courses',
    SETTINGS: '/admin/settings',
  },
  KIDS: {
    HOME: '/kids',
    CS: '/kids/cs',
    MATH: '/kids/math',
    GAMES: '/kids/games',
  },
} as const;

export const XP = {
  DEFAULT_LESSON: 10,
  DEFAULT_QUIZ: 5,
  XP_PER_LEVEL: 1000,
  MAX_CODE_LENGTH: 100_000,
  STREAK_BONUS: 10,
} as const;
